import type { Metadata } from 'next'
import { PageProvider } from '@/context/Provider'
import { Separator } from '@/components/ui/separator'
import { Toaster } from "@/components/ui/sonner"
import { Nunito } from 'next/font/google'
import Cart from '@/components/shared/Cart'
import Image from 'next/image'
import Dropdown from '@/components/shared/Dropdown'
import Feedbacks from '@/components/shared/form/Feedbacks'
import 'swiper/css';
import 'swiper/css/effect-coverflow';
import 'swiper/css/pagination';
import './globals.css'
import BottomNav from '@/components/shared/BottomNav'

const nunito = Nunito({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Gamestore',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${nunito.className} blackBg text-white`}>
        <PageProvider>
          <main className='w-full relative'>
            {children}
            <BottomNav />
            <Cart />
            <Dropdown className='hidden right-0 bottom-0 gap-6 w-14 h-14 sm:block' image={<Image src='/elipse.gif' className='absolute z-10 m-auto inset-0 object-cover' width={40} height={40} alt='icon' />}>
              <h2 className="text-center">Portal de feedbacks</h2>
              <Separator className="my-4 bg-slate-700" />
              <Feedbacks />
            </Dropdown>
          </main>
          <Toaster />
        </PageProvider>
      </body>
    </html>
  )
}
