import type { Metadata } from 'next'
import { PageProvider } from '@/context/Provider'
import { Nunito } from 'next/font/google'
import { Toaster } from "@/components/ui/sonner"
import Cart from '@/components/shared/Cart'
import 'swiper/css';
import 'swiper/css/effect-coverflow';
import 'swiper/css/pagination';
import './globals.css'
import Footer from '@/components/views/Footer'
import Feedback from '@/components/shared/Feedback'

const nunito = Nunito({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${nunito.className} blackBg text-white`}>
        <PageProvider>
          <main className='w-full relative'>
            {children}
            <Cart />
            <Feedback />
          </main>
          <Toaster />
        </PageProvider>
      </body>
    </html>
  )
}
