import { MagnifyingGlassIcon, PencilSquareIcon, ChevronUpIcon, GlobeEuropeAfricaIcon, MapPinIcon, EnvelopeIcon, CalendarDaysIcon, CameraIcon, PhoneIcon, GifIcon, FaceSmileIcon, PaperAirplaneIcon, ArrowUturnRightIcon, MicrophoneIcon, HeartIcon, UserIcon, ChatBubbleBottomCenterIcon, ChevronDownIcon, XMarkIcon, HomeIcon, LightBulbIcon } from '@heroicons/react/24/solid'
export const Icon = {
   chat: ChatBubbleBottomCenterIcon,
   calendarDay: CalendarDaysIcon,
   chevronDown: ChevronDownIcon,
   chevronUp: ChevronUpIcon,
   globe: GlobeEuropeAfricaIcon,
   search: MagnifyingGlassIcon,
   microphone: MicrophoneIcon,
   reply: ArrowUturnRightIcon,
   pencil: PencilSquareIcon,
   send: PaperAirplaneIcon,
   envelope: EnvelopeIcon,
   light: LightBulbIcon,
   emoj: FaceSmileIcon,
   camera: CameraIcon,
   phone: PhoneIcon,
   photo: PhoneIcon,
   heart: HeartIcon,
   close: XMarkIcon,
   pin: MapPinIcon,
   home: HomeIcon,
   user: UserIcon,
   gif: GifIcon,
}